// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kczhfznwxkbjuqfbouin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjemhmem53eGtianVxZmJvdWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5Mzc3MTMsImV4cCI6MjA0OTUxMzcxM30.DIALgl8hEM9OwtzJ_RywmUk8NsxrYy2jEvC5WCfDLj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);